import { writeFile } from "node:fs/promises";
import { join } from "node:path";

const ROOT = process.cwd();

const citations = {
  yeo2011: {
    doi: "10.1152/jn.00338.2011",
    year: 2011,
    journal: "Journal of Neurophysiology",
    title: "The organization of the human cerebral cortex estimated by intrinsic functional connectivity",
  },
  hong2019: {
    doi: "10.1038/s41467-019-08944-1",
    year: 2019,
    journal: "Nature Communications",
    title: "Atypical functional connectome hierarchy in autism",
  },
  seeley2007: {
    doi: "10.1523/JNEUROSCI.5587-06.2007",
    year: 2007,
    journal: "Journal of Neuroscience",
    title: "Dissociable intrinsic connectivity networks for salience processing and executive control",
  },
  menonUddin2010: {
    doi: "10.1007/s00429-010-0262-0",
    year: 2010,
    journal: "Brain Structure and Function",
    title: "Saliency, switching, attention and control: a network model of insula function",
  },
  menon2011: {
    doi: "10.1016/j.tics.2011.08.003",
    year: 2011,
    journal: "Trends in Cognitive Sciences",
    title: "Large-scale brain networks and psychopathology: a unifying triple network model",
  },
  hickokPoeppel2007: {
    doi: "10.1038/nrn2113",
    year: 2007,
    journal: "Nature Reviews Neuroscience",
    title: "The cortical organization of speech processing",
  },
  knoblauch1999: {
    doi: "10.1212/WNL.52.5.1038",
    year: 1999,
    journal: "Neurology",
    title: "Cerebral lateralization of language in normal left-handed people studied by functional MRI",
  },
  goodaleMilner1992: {
    doi: "10.1016/0166-2236(92)90344-8",
    year: 1992,
    journal: "Trends in Neurosciences",
    title: "Separate visual pathways for perception and action",
  },
  kanwisher1997: {
    doi: "10.1523/JNEUROSCI.17-11-04302.1997",
    year: 1997,
    journal: "Journal of Neuroscience",
    title: "The fusiform face area: a module in human extrastriate cortex specialized for face perception",
  },
  cohen2002: {
    doi: "10.1093/brain/awf094",
    year: 2002,
    journal: "Brain",
    title: "Language-specific tuning of visual cortex? Functional properties of the Visual Word Form Area",
  },
  epsteinKanwisher1998: {
    doi: "10.1038/33402",
    year: 1998,
    journal: "Nature",
    title: "A cortical representation of the local visual environment",
  },
  hackett2011: {
    doi: "10.1016/j.heares.2010.01.011",
    year: 2011,
    journal: "Hearing Research",
    title: "Information flow in the auditory cortical network",
  },
  schurz2014: {
    doi: "10.1016/j.neubiorev.2014.01.009",
    year: 2014,
    journal: "Neuroscience & Biobehavioral Reviews",
    title: "Fractionating theory of mind: a meta-analysis of functional brain imaging studies",
  },
  mukamel2010: {
    doi: "10.1016/j.cub.2010.02.045",
    year: 2010,
    journal: "Current Biology",
    title: "Single-neuron responses in humans during execution and observation of actions",
  },
  wasserthal2018: {
    doi: "10.1016/j.neuroimage.2018.07.070",
    year: 2018,
    journal: "NeuroImage",
    title: "TractSeg - Fast and accurate white matter tract segmentation",
  },
  poulin2020: {
    doi: "10.1016/j.tins.2020.01.004",
    year: 2020,
    journal: "Trends in Neurosciences",
    title: "Classification of midbrain dopamine neurons using single-cell gene expression profiling approaches",
  },
  garritsen2023: {
    doi: "10.1038/s41583-022-00669-3",
    year: 2023,
    journal: "Nature Reviews Neuroscience",
    title: "Development, wiring and function of dopamine neuron subtypes",
  },
  okaty2019: {
    doi: "10.1038/s41583-019-0151-3",
    year: 2019,
    journal: "Nature Reviews Neuroscience",
    title: "Embracing diversity in the 5-HT neuronal system",
  },
  ren2019: {
    doi: "10.7554/eLife.49424",
    year: 2019,
    journal: "eLife",
    title: "Single-cell transcriptomes and whole-brain projections of serotonin neurons in the mouse dorsal and median raphe nuclei",
  },
  reyes2025: {
    doi: "10.1111/ejn.70111",
    year: 2025,
    journal: "European Journal of Neuroscience",
    title: "The Locus Coeruleus: Anatomy, Physiology, and Stress-Related Neuropsychiatric Disorders",
  },
  thannickal2000: {
    doi: "10.1016/s0896-6273(00)00058-1",
    year: 2000,
    journal: "Neuron",
    title: "Reduced number of hypocretin neurons in human narcolepsy",
  },
  kano2009: {
    doi: "10.1152/physrev.00019.2008",
    year: 2009,
    journal: "Physiological Reviews",
    title: "Endocannabinoid-mediated control of synaptic transmission",
  },
  traynelis2010: {
    doi: "10.1124/pr.109.002451",
    year: 2010,
    journal: "Pharmacological Reviews",
    title: "Glutamate receptor ion channels: structure, regulation, and function",
  },
  olsen2008: {
    doi: "10.1016/j.neuropharm.2008.07.045",
    year: 2008,
    journal: "Neuropharmacology",
    title: "GABAA receptors: subtypes provide diversity of function and pharmacology",
  },
  haas2008: {
    doi: "10.1152/physrev.00043.2007",
    year: 2008,
    journal: "Physiological Reviews",
    title: "Histamine in the nervous system",
  },
};

const cite = (...keys) => keys.map((key) => citations[key]);

function node(name, hcp, julich, role, xyz) {
  return { name, hcp_mmp1: hcp, julich, role, xyz };
}

const networks = [
  {
    slug: "yeo-default-mode",
    name: "Default mode network",
    system: "Yeo 7-network",
    color: "#e11d48",
    tier: 1,
    description: "Medial prefrontal, posterior cingulate, angular, precuneus, and medial temporal nodes with high intrinsic coupling.",
    key_regions: ["mPFC", "PCC", "angular gyrus", "precuneus", "hippocampus"],
    core_nodes: [
      node("medial prefrontal cortex", ["10mp", "10v", "10r"], ["Fp1/Fp2 proxy"], "self-reference and valuation", [-0.02, 0.62, 0.28]),
      node("posterior cingulate cortex", ["23d", "31a", "31pd"], ["Area 23/31 proxy"], "autobiographical integration", [0, -0.48, 0.42]),
      node("angular gyrus", ["PGi", "PGs"], ["PGa/PGp proxy"], "semantic and ToM integration", [-0.52, -0.52, 0.34]),
      node("precuneus", ["7m"], ["Area 7m proxy"], "scene/self model", [0, -0.62, 0.62]),
      node("hippocampus", ["HCPex hippocampus"], ["Hippocampal formation"], "episodic recall", [-0.28, -0.28, -0.18]),
    ],
    function_claims: ["self-reference", "mind-wandering", "episodic recall", "theory of mind"],
    connectivity: "High resting-state coupling along the transmodal apex of the Margulies principal gradient; anti-correlated with externally oriented attention/control states in many task contexts.",
    disorders: ["Alzheimer disease hyper- to hypoconnectivity trajectory", "major depression hyperconnectivity", "autism atypical hierarchy"],
    overlay: { kind: "cortex", visible: true },
    citations: cite("yeo2011", "hong2019", "menon2011"),
  },
  {
    slug: "salience",
    name: "Salience network",
    system: "Yeo 7-network / triple network",
    color: "#f97316",
    tier: 1,
    description: "Anterior insula, dorsal anterior cingulate, and amygdala-centered network for salience detection and control switching.",
    key_regions: ["anterior insula", "dACC", "amygdala"],
    core_nodes: [
      node("anterior insula", ["AVI", "MI"], ["Ig1/Ig2 proxy"], "interoceptive salience", [-0.52, 0.12, 0.12]),
      node("dorsal anterior cingulate", ["24dd", "32"], ["Area 24/32 proxy"], "control mobilization", [0, 0.24, 0.54]),
      node("amygdala", ["HCPex amygdala"], ["Amygdaloid complex"], "affective salience", [-0.31, -0.1, -0.2]),
    ],
    function_claims: ["switching between DMN and CEN", "salience detection", "autonomic control"],
    connectivity: "Anterior insula and dACC couple with limbic/subcortical nodes and engage frontoparietal control during salient events.",
    disorders: ["frontotemporal dementia", "addiction"],
    overlay: { kind: "cortex", visible: true },
    citations: cite("yeo2011", "menonUddin2010", "seeley2007"),
  },
  {
    slug: "frontoparietal-control",
    name: "Central executive / frontoparietal control network",
    system: "Yeo 7-network / triple network",
    color: "#0ea5e9",
    tier: 1,
    description: "Dorsolateral prefrontal and posterior parietal control network supporting working memory and flexible task control.",
    key_regions: ["dlPFC", "IPS", "posterior parietal cortex"],
    core_nodes: [
      node("dorsolateral prefrontal cortex", ["46", "9-46d", "9-46v"], ["Area 46 proxy"], "working memory", [-0.38, 0.42, 0.38]),
      node("intraparietal sulcus", ["IP0", "IP1", "IP2"], ["hIP1/hIP2/hIP3 proxy"], "task-rule attention", [-0.44, -0.42, 0.48]),
    ],
    function_claims: ["working memory", "cognitive control", "goal maintenance"],
    connectivity: "Flexible frontoparietal coupling with task-relevant sensory and association systems.",
    disorders: ["schizophrenia working-memory deficits"],
    overlay: { kind: "cortex", visible: true },
    citations: cite("yeo2011", "menon2011", "seeley2007"),
  },
  {
    slug: "dorsal-attention",
    name: "Dorsal attention network",
    system: "Yeo 7-network",
    color: "#22c55e",
    tier: 1,
    description: "Frontal eye fields, intraparietal sulcus, and MT+ nodes for top-down spatial attention.",
    key_regions: ["FEF", "IPS", "MT+"],
    core_nodes: [
      node("frontal eye field", ["FEF"], ["FEF proxy"], "top-down gaze and attention", [-0.32, -0.04, 0.58]),
      node("intraparietal sulcus", ["IP0", "IP1", "IP2"], ["hIP proxy"], "priority maps", [-0.42, -0.46, 0.52]),
      node("MT+", ["MT", "MST"], ["hOc5/MT proxy"], "motion attention", [-0.48, -0.68, 0.08]),
    ],
    function_claims: ["top-down spatial attention", "visuomotor orienting"],
    connectivity: "Couples frontal eye fields and parietal priority maps with motion-sensitive visual cortex.",
    disorders: ["spatial attention impairment after dorsal frontoparietal lesions"],
    overlay: { kind: "cortex", visible: true },
    citations: cite("yeo2011", "goodaleMilner1992"),
  },
  {
    slug: "ventral-attention",
    name: "Ventral attention network",
    system: "Yeo 7-network",
    color: "#f59e0b",
    tier: 1,
    description: "Right-lateralized temporoparietal and ventral frontal network for stimulus-driven reorienting.",
    key_regions: ["right TPJ", "ventral frontal cortex"],
    core_nodes: [
      node("temporoparietal junction", ["TPOJ1", "TPOJ2", "TPOJ3"], ["TPJ proxy"], "bottom-up reorienting", [0.54, -0.42, 0.3]),
      node("ventral frontal cortex", ["44", "45", "IFJa"], ["Area 44/45 proxy"], "interrupt/reorient", [0.42, 0.18, 0.22]),
    ],
    function_claims: ["bottom-up reorienting", "unexpected-event detection"],
    connectivity: "Right-biased TPJ and ventral frontal nodes interrupt ongoing dorsal-attention states.",
    disorders: ["right hemisphere stroke hemineglect"],
    overlay: { kind: "cortex", visible: true },
    citations: cite("yeo2011", "menonUddin2010"),
  },
  {
    slug: "somatomotor",
    name: "Somatomotor network",
    system: "Yeo 7-network",
    color: "#06b6d4",
    tier: 1,
    description: "Precentral, postcentral, supplementary motor, and auditory-adjacent sensorimotor cortex.",
    key_regions: ["M1", "S1", "SMA", "A1"],
    core_nodes: [
      node("primary motor cortex", ["4"], ["Area 4a/4p"], "descending motor output", [-0.38, -0.22, 0.64]),
      node("primary somatosensory cortex", ["3a", "3b", "1", "2"], ["Areas 3a/3b/1/2"], "body surface input", [-0.42, -0.32, 0.64]),
      node("supplementary motor area", ["6mp", "SCEF"], ["SMA proxy"], "sequence initiation", [0, -0.05, 0.68]),
      node("primary auditory cortex", ["A1", "Te1.0"], ["Te1.0"], "auditory sensorimotor coupling", [-0.48, -0.22, 0.04]),
    ],
    function_claims: ["sensorimotor control", "somatotopy", "motor-auditory coupling"],
    connectivity: "Perirolandic homotopic connectivity with cerebellar, thalamic, and corticospinal/corticobulbar routes.",
    disorders: ["motor stroke", "dystonia", "sensorimotor integration disorders"],
    overlay: { kind: "cortex", visible: true },
    citations: cite("yeo2011", "wasserthal2018"),
  },
  {
    slug: "visual",
    name: "Visual network",
    system: "Yeo 7-network",
    color: "#8b5cf6",
    tier: 1,
    description: "Occipital visual cortex spanning V1/V2/V3/V4/MT+ and downstream dorsal/ventral visual streams.",
    key_regions: ["V1", "V2", "V3", "V4", "MT+"],
    core_nodes: [
      node("primary visual cortex", ["V1"], ["hOc1"], "retinotopic input", [0, -0.86, 0.18]),
      node("extrastriate cortex", ["V2", "V3", "V4"], ["hOc2/hOc3/hOc4"], "feature extraction", [-0.22, -0.78, 0.18]),
      node("MT+", ["MT", "MST"], ["hOc5/MT"], "motion processing", [-0.48, -0.68, 0.06]),
    ],
    function_claims: ["vision", "motion processing", "object and spatial stream routing"],
    connectivity: "Retinotopic visual cortex routes dorsal where/how and ventral what-stream projections.",
    disorders: ["cortical blindness", "achromatopsia", "prosopagnosia"],
    overlay: { kind: "cortex", visible: true },
    citations: cite("yeo2011", "goodaleMilner1992", "kanwisher1997"),
  },
  {
    slug: "limbic",
    name: "Limbic network",
    system: "Yeo 7-network",
    color: "#ec4899",
    tier: 2,
    description: "Temporal pole, orbitofrontal, and subgenual network with lower fMRI reliability because of susceptibility signal drop-out.",
    key_regions: ["temporal pole", "OFC", "subgenual cortex"],
    core_nodes: [
      node("temporal pole", ["TGd", "TGv"], ["Temporal pole proxy"], "semantic-affective memory", [-0.52, 0.18, -0.24]),
      node("orbitofrontal cortex", ["11l", "13l", "OFC"], ["Fo1/Fo2 proxy"], "reward valuation", [-0.24, 0.5, -0.24]),
      node("subgenual cortex", ["25"], ["Area 25 proxy"], "mood regulation", [0, 0.22, -0.18]),
    ],
    function_claims: ["reward and emotion mapping"],
    connectivity: "Orbitofrontal and temporal-pole coupling is biologically plausible but fMRI signal loss lowers confidence.",
    disorders: ["depression", "addiction"],
    overlay: { kind: "cortex", visible: true },
    citations: cite("yeo2011", "menon2011"),
  },
  {
    slug: "triple-network",
    name: "Triple-network switching model",
    system: "Control model",
    color: "#f97316",
    tier: 1,
    description: "Salience network switching between the default-mode and central executive networks in cognition and psychopathology.",
    key_regions: ["SN", "DMN", "CEN"],
    core_nodes: [],
    function_claims: ["SN switches DMN and CEN modes", "large-scale psychiatric network model"],
    connectivity: "Anterior insula/dACC gate transitions between internally directed DMN states and externally directed CEN control.",
    disorders: ["mood disorders", "anxiety", "psychosis", "addiction"],
    overlay: { kind: "switch", visible: true },
    citations: cite("menon2011", "menonUddin2010", "seeley2007"),
  },
  {
    slug: "language",
    name: "Dual-stream language network",
    system: "Task-defined association network",
    color: "#14b8a6",
    tier: 1,
    description: "Dorsal sound-to-articulation and ventral sound-to-meaning streams linking temporal and inferior frontal cortex.",
    key_regions: ["superior temporal cortex", "arcuate fasciculus", "Broca 44/45", "IFG"],
    core_nodes: [
      node("posterior superior temporal cortex", ["STSdp", "A5"], ["Te3/STG proxy"], "phonological analysis", [-0.52, -0.26, 0.12]),
      node("Broca complex", ["44", "45"], ["Area 44/45"], "speech production and syntax", [-0.45, 0.18, 0.22]),
      node("middle temporal cortex", ["TE1m", "TE2"], ["MTG proxy"], "lexical-semantic mapping", [-0.58, -0.34, 0.02]),
    ],
    function_claims: ["dorsal sound-to-articulation stream", "ventral sound-to-meaning stream", "conduction aphasia after arcuate disruption"],
    connectivity: "Dorsal stream routes superior temporal cortex through SLF/arcuate to premotor/Broca; ventral stream routes superior/middle temporal cortex through ILF/IFOF to IFG.",
    disorders: ["conduction aphasia", "semantic aphasia"],
    streams: [
      { name: "Dorsal stream", route: ["superior temporal", "SLF/arcuate", "premotor", "Broca 44/45"], function: "sound -> articulation" },
      { name: "Ventral stream", route: ["superior/middle temporal", "ILF/IFOF", "inferior frontal"], function: "sound -> meaning" },
    ],
    lateralization: {
      rightHandersLeftPercent: 96,
      leftHandersLeftPercent: 76,
      bilateralPercent: 14,
      rightHemispherePercent: 10,
    },
    overlay: { kind: "streams", visible: true },
    citations: cite("hickokPoeppel2007", "knoblauch1999", "wasserthal2018"),
  },
  {
    slug: "vision-dorsal-stream",
    name: "Dorsal visual where/how stream",
    system: "Vision stream",
    color: "#22c55e",
    tier: 1,
    description: "Occipital-to-parietal/premotor visual stream for spatial action and motion-guided behavior.",
    key_regions: ["V1", "V2", "V3", "V3A", "MT+", "IPS", "PMd"],
    core_nodes: [],
    function_claims: ["spatial localization", "visuomotor action guidance"],
    connectivity: "V1 -> V2 -> V3 -> V3A -> MT+ -> IPS -> PMd.",
    disorders: ["optic ataxia", "dorsal simultanagnosia"],
    streams: [{ name: "Dorsal where/how", route: ["V1", "V2", "V3", "V3A", "MT+", "IPS", "PMd"], function: "vision for action" }],
    overlay: { kind: "streams", visible: true },
    citations: cite("goodaleMilner1992", "yeo2011"),
  },
  {
    slug: "vision-ventral-stream",
    name: "Ventral visual what stream",
    system: "Vision stream",
    color: "#8b5cf6",
    tier: 1,
    description: "Occipital-to-temporal visual stream for object, face, place, and word-form recognition.",
    key_regions: ["V1", "V2", "V4", "fusiform", "anterior temporal"],
    core_nodes: [],
    function_claims: ["object recognition", "face processing", "visual word form processing", "place processing"],
    connectivity: "V1 -> V2 -> V4 -> fusiform -> anterior temporal cortex, including FFA, VWFA, and PPA nodes.",
    disorders: ["prosopagnosia", "pure alexia", "topographic disorientation"],
    streams: [{ name: "Ventral what", route: ["V1", "V2", "V4", "fusiform", "anterior temporal"], function: "object identity" }],
    overlay: { kind: "streams", visible: true },
    citations: cite("goodaleMilner1992", "kanwisher1997", "cohen2002", "epsteinKanwisher1998"),
  },
  {
    slug: "motor-network",
    name: "Motor network",
    system: "Effector network",
    color: "#06b6d4",
    tier: 1,
    description: "M1, premotor, SMA, pre-SMA, and cingulate motor nodes linked to pyramidal and extrapyramidal output systems.",
    key_regions: ["M1", "PMd", "PMv", "SMA", "pre-SMA", "CMA"],
    core_nodes: [
      node("M1", ["4"], ["Area 4a/4p"], "corticospinal output", [-0.42, -0.2, 0.64]),
      node("PMd", ["6d"], ["Area 6d proxy"], "reach planning", [-0.34, 0.02, 0.58]),
      node("PMv", ["6v"], ["Area 6v proxy"], "grasp/orofacial premotor", [-0.48, 0.04, 0.22]),
      node("SMA", ["6mp", "SCEF"], ["SMA proxy"], "sequence initiation", [0, -0.04, 0.68]),
      node("pre-SMA", ["SFL"], ["pre-SMA proxy"], "action selection", [0, 0.18, 0.66]),
      node("cingulate motor area", ["24c"], ["Area 24c proxy"], "motivated action", [0, 0.02, 0.48]),
    ],
    function_claims: ["voluntary movement", "motor planning", "corticospinal and corticobulbar output"],
    connectivity: "Pyramidal tracts include corticospinal and corticobulbar outputs; extrapyramidal routes include rubrospinal, reticulospinal, vestibulospinal, and tectospinal systems.",
    disorders: ["stroke", "Parkinson disease motor circuit dysfunction", "dystonia"],
    homunculus: ["foot medial", "leg", "trunk", "hand", "face lateral"],
    overlay: { kind: "homunculus", visible: true },
    citations: cite("yeo2011", "wasserthal2018"),
  },
  {
    slug: "somatosensory-network",
    name: "Somatosensory network",
    system: "Sensory network",
    color: "#38bdf8",
    tier: 1,
    description: "S1, S2, and posterior parietal integration network organized around somatotopic body maps.",
    key_regions: ["S1", "S2", "PPC"],
    core_nodes: [
      node("S1", ["3a", "3b", "1", "2"], ["Areas 3a/3b/1/2"], "primary tactile/proprioceptive map", [-0.44, -0.34, 0.62]),
      node("S2", ["OP1", "OP4"], ["Parietal operculum proxy"], "bilateral tactile integration", [-0.52, -0.22, 0.02]),
      node("posterior parietal cortex", ["5L", "7AL", "7PC"], ["Area 5/7 proxy"], "multisensory body schema", [-0.36, -0.48, 0.58]),
    ],
    function_claims: ["somatosensation", "homunculus mapping", "body-schema integration"],
    connectivity: "Thalamocortical input to S1 is relayed to S2 and posterior parietal association cortex.",
    disorders: ["cortical sensory loss", "astereognosis", "body-schema disorders"],
    homunculus: ["foot medial", "leg", "trunk", "hand", "face lateral"],
    overlay: { kind: "homunculus", visible: true },
    citations: cite("yeo2011"),
  },
  {
    slug: "auditory-network",
    name: "Auditory core-belt-parabelt network",
    system: "Sensory network",
    color: "#facc15",
    tier: 1,
    description: "Hackett core/belt/parabelt auditory hierarchy centered on Heschl and superior temporal cortex.",
    key_regions: ["A1 / Te1.0", "belt", "parabelt"],
    core_nodes: [
      node("auditory core", ["A1", "Te1.0"], ["Te1.0"], "tonotopic core", [-0.46, -0.22, 0.06]),
      node("belt", ["MBelt", "LBelt"], ["Belt proxy"], "spectrotemporal features", [-0.54, -0.24, 0.02]),
      node("parabelt", ["PBelt"], ["Parabelt proxy"], "auditory association", [-0.58, -0.28, 0]),
    ],
    function_claims: ["audition", "core-belt-parabelt processing"],
    connectivity: "Hierarchical auditory information flow from A1 core through belt to parabelt association cortex.",
    disorders: ["cortical deafness", "auditory agnosia"],
    overlay: { kind: "cortex", visible: true },
    citations: cite("hackett2011", "yeo2011"),
  },
  {
    slug: "theory-of-mind",
    name: "Theory of mind network",
    system: "Social cognition network",
    color: "#a78bfa",
    tier: 1,
    description: "TPJ, mPFC, precuneus, and pSTS network for reasoning about beliefs, intentions, and social agents.",
    key_regions: ["TPJ", "mPFC", "precuneus", "pSTS"],
    core_nodes: [
      node("TPJ", ["TPOJ1", "TPOJ2", "TPOJ3"], ["TPJ proxy"], "belief reasoning", [0.52, -0.45, 0.34]),
      node("mPFC", ["9m", "10v"], ["mPFC proxy"], "social self/other model", [0, 0.54, 0.34]),
      node("precuneus", ["PCV", "7m"], ["Precuneus proxy"], "scene and agent context", [0, -0.58, 0.54]),
      node("pSTS", ["STSdp", "TPOJ"], ["pSTS proxy"], "biological motion and agency", [0.55, -0.42, 0.08]),
    ],
    function_claims: ["belief attribution", "mental-state reasoning", "social prediction"],
    connectivity: "Overlaps the transmodal DMN apex but emphasizes TPJ/pSTS social-inference nodes.",
    disorders: ["autism spectrum social-cognition differences"],
    overlay: { kind: "cortex", visible: true },
    citations: cite("schurz2014", "hong2019", "yeo2011"),
  },
  {
    slug: "mirror-neuron-system",
    name: "Mirror neuron system",
    system: "Action-observation network",
    color: "#f59e0b",
    tier: 2,
    description: "Inferior parietal, ventral premotor/F5-like, and STS action-observation scaffold; human single-unit confirmation remains limited.",
    key_regions: ["inferior parietal", "ventral premotor F5-like", "STS"],
    core_nodes: [
      node("inferior parietal", ["PFt", "PF", "PFcm"], ["PF proxy"], "observed-action mapping", [-0.48, -0.4, 0.44]),
      node("ventral premotor", ["6v", "44"], ["Area 6v/44 proxy"], "action repertoire", [-0.46, 0.02, 0.22]),
      node("STS", ["STSdp", "STSvp"], ["STS proxy"], "visual action input", [-0.54, -0.36, 0.08]),
    ],
    function_claims: ["action observation to execution mapping"],
    connectivity: "STS visual action input converges with inferior parietal and ventral premotor action representations.",
    disorders: ["social cognition hypotheses remain debated"],
    note: "Marked plausible because human direct single-unit evidence is limited compared with macaque data.",
    overlay: { kind: "cortex", visible: true },
    citations: cite("mukamel2010", "schurz2014"),
  },
];

const neuromodulators = [
  {
    slug: "dopamine",
    name: "Dopamine",
    abbreviation: "DA",
    color: "#22c55e",
    tier: 1,
    nuclei: ["substantia nigra pars compacta A9", "ventral tegmental area A10", "arcuate A12", "incertohypothalamic A13"],
    projections: ["dorsal striatum", "nucleus accumbens", "amygdala", "hippocampus", "prefrontal cortex", "ACC", "median eminence"],
    cell_body_locations: [
      { name: "SNc A9", xyz: [-0.16, -0.34, -0.42] },
      { name: "VTA A10", xyz: [0, -0.32, -0.4] },
      { name: "arcuate A12", xyz: [0, -0.08, -0.35] },
    ],
    projection_fields: ["nigrostriatal", "mesolimbic", "mesocortical", "tuberoinfundibular", "incertohypothalamic"],
    pathways: [
      "nigrostriatal A9 -> dorsal striatum; motor; depleted in Parkinson disease",
      "mesolimbic A10 -> nucleus accumbens, amygdala, hippocampus; reward and motivation",
      "mesocortical A10 -> PFC/ACC; cognition and working memory",
      "tuberoinfundibular A12 -> median eminence; prolactin inhibition",
      "incertohypothalamic A13",
    ],
    receptors: ["D1", "D2", "D3", "D4", "D5"],
    taxonomy: ["Poulin 2020: single-cell gene-expression classification of midbrain DA neurons", "Garritsen 2023: development, wiring, and function of DA neuron subtypes", "A10 VTA Calb1+ subgroup relatively less vulnerable", "SNc Sox6+Aldh1a1+ subtype vulnerable in PD"],
    clinical_notes: ["Parkinson disease", "addiction", "psychosis pharmacology", "prolactin regulation"],
    citations: cite("poulin2020", "garritsen2023"),
  },
  {
    slug: "serotonin",
    name: "Serotonin",
    abbreviation: "5-HT",
    color: "#ef4444",
    tier: 1,
    nuclei: ["dorsal raphe", "median raphe", "caudal raphe"],
    projections: ["cortex", "amygdala", "striatum", "hippocampus", "septum", "spinal cord"],
    cell_body_locations: [
      { name: "dorsal raphe", xyz: [0, -0.45, -0.18] },
      { name: "median raphe", xyz: [0, -0.5, -0.24] },
    ],
    projection_fields: ["DR -> cortex/amygdala/striatum", "MR -> hippocampus/septum", "caudal raphe -> spinal cord"],
    pathways: ["11 transcriptomic 5-HT clusters from Ren 2019", "amygdala-projecting DR 5-HT anxiety-related", "frontal-cortex-projecting DR 5-HT active coping-related"],
    receptors: ["5-HT1A", "5-HT1B", "5-HT1D", "5-HT2A", "5-HT2C", "5-HT3", "5-HT4", "5-HT5", "5-HT6", "5-HT7"],
    taxonomy: ["5-HT2A psychedelic target", "5-HT3 ionotropic antiemetic target"],
    clinical_notes: ["depression", "anxiety", "psychedelic pharmacology", "antiemesis"],
    citations: cite("okaty2019", "ren2019"),
  },
  {
    slug: "norepinephrine",
    name: "Norepinephrine",
    abbreviation: "NE",
    color: "#06b6d4",
    tier: 1,
    nuclei: ["locus coeruleus A6", "lateral tegmental A1/A2/A5/A7"],
    projections: ["entire cerebral cortex", "hippocampus", "cerebellum", "hypothalamus", "spinal cord"],
    cell_body_locations: [{ name: "LC A6", xyz: [0, -0.55, -0.12] }],
    projection_fields: ["LC -> cortex", "LC -> hippocampus", "lateral tegmental NE -> hypothalamus/spinal cord"],
    pathways: ["LC is the sole cortical NE source", "22,000-51,000 bilateral pigmented neurons in adult human stereological estimates", "early Alzheimer vulnerability"],
    receptors: ["alpha1", "alpha2", "beta1", "beta2", "beta3"],
    taxonomy: ["LC stress/arousal ensembles", "lateral tegmental autonomic NE groups"],
    clinical_notes: ["arousal", "attention", "stress", "Alzheimer disease vulnerability"],
    citations: cite("reyes2025"),
  },
  {
    slug: "acetylcholine",
    name: "Acetylcholine",
    abbreviation: "ACh",
    color: "#facc15",
    tier: 1,
    nuclei: ["medial septal nucleus Ch1", "diagonal band Ch2/Ch3", "nucleus basalis of Meynert Ch4", "PPN Ch5", "LDT Ch6", "striatal TANs"],
    projections: ["hippocampus", "cortex", "thalamus", "reticular formation", "striatum"],
    cell_body_locations: [
      { name: "NBM Ch4", xyz: [0, 0.05, -0.22] },
      { name: "PPN/LDT", xyz: [0, -0.48, -0.24] },
    ],
    projection_fields: ["basal forebrain -> cortex/hippocampus", "PPN/LDT -> thalamus/reticular formation", "striatal TAN local modulation"],
    pathways: ["NBM/Ch4 degenerates early in Alzheimer disease", "AChE inhibitor drug rationale: donepezil, rivastigmine, galantamine", "brainstem cholinergic REM and arousal"],
    receptors: ["muscarinic M1", "M2", "M3", "M4", "M5", "nicotinic alpha2-alpha10", "nicotinic beta2-beta4", "alpha7"],
    taxonomy: ["basal forebrain Ch1-Ch4", "brainstem Ch5-Ch6", "striatal cholinergic interneurons"],
    clinical_notes: ["Alzheimer disease", "REM sleep", "arousal", "attention"],
    citations: cite("menonUddin2010", "reyes2025"),
  },
  {
    slug: "glutamate",
    name: "Glutamate",
    abbreviation: "Glu",
    color: "#a3e635",
    tier: 1,
    nuclei: ["cortical pyramidal neurons", "thalamocortical relay neurons", "cerebellar granule cells"],
    projections: ["cortico-cortical", "thalamocortical", "corticostriatal", "parallel fibers"],
    cell_body_locations: [{ name: "cortex", xyz: [0, 0, 0.72] }, { name: "thalamus", xyz: [0, -0.12, 0.02] }],
    projection_fields: ["principal excitatory transmission", "feedforward thalamocortical drive", "cerebellar parallel fibers"],
    pathways: ["AMPA fast EPSCs", "NMDA coincidence/plasticity receptor", "kainate modulation", "mGluR group I/II/III"],
    receptors: ["AMPA GluA1-4", "NMDA GluN1/GluN2A-D/GluN3A-B", "Kainate GluK1-5", "mGluR1-8"],
    taxonomy: ["cortical IT/ET/NP/CT/L6b excitatory classes"],
    clinical_notes: ["plasticity", "excitotoxicity", "epilepsy pharmacology"],
    citations: cite("traynelis2010"),
  },
  {
    slug: "gaba",
    name: "GABA",
    abbreviation: "GABA",
    color: "#60a5fa",
    tier: 1,
    nuclei: ["cortical interneurons", "Purkinje cells", "striatal SPNs", "GPe", "GPi", "SNr"],
    projections: ["local cortical inhibition", "cerebellar output inhibition", "basal ganglia inhibitory pathways"],
    cell_body_locations: [{ name: "interneurons", xyz: [0, 0, 0.64] }, { name: "basal ganglia", xyz: [0.22, 0.02, -0.06] }],
    projection_fields: ["PV/SST/VIP/LAMP5/SNCG interneuron classes", "Purkinje -> deep cerebellar nuclei", "GPe/GPi/SNr basal ganglia output"],
    pathways: ["principal inhibitory neurotransmitter", "benzodiazepine/ethanol/anesthetic modulation at GABA-A", "baclofen target at GABA-B"],
    receptors: ["GABA-A", "GABA-B"],
    taxonomy: ["PV basket/chandelier", "SST Martinotti/non-Martinotti", "VIP disinhibitory", "LAMP5 neurogliaform", "SNCG/CCK basket"],
    clinical_notes: ["anxiety pharmacology", "epilepsy", "spasticity"],
    citations: cite("olsen2008"),
  },
  {
    slug: "histamine",
    name: "Histamine",
    abbreviation: "His",
    color: "#a855f7",
    tier: 1,
    nuclei: ["tuberomammillary nucleus"],
    projections: ["cortex", "thalamus", "basal forebrain", "hypothalamus"],
    cell_body_locations: [{ name: "TMN", xyz: [0, -0.2, -0.28] }],
    projection_fields: ["TMN -> cortex", "TMN -> thalamus", "TMN -> hypothalamus"],
    pathways: ["TMN is the sole histaminergic source", "wakefulness promotion", "H1 antagonists cause sedation"],
    receptors: ["H1", "H2", "H3", "H4"],
    taxonomy: ["posterior hypothalamic histaminergic neurons"],
    clinical_notes: ["wakefulness", "sedation from H1 antagonists"],
    citations: cite("haas2008"),
  },
  {
    slug: "orexin-hypocretin",
    name: "Orexin / hypocretin",
    abbreviation: "Hcrt",
    color: "#fb923c",
    tier: 1,
    nuclei: ["lateral hypothalamic area"],
    projections: ["LC", "raphe", "TMN", "VTA", "basal forebrain", "cortex"],
    cell_body_locations: [{ name: "lateral hypothalamus", xyz: [0.18, -0.16, -0.28] }],
    projection_fields: ["LH orexin -> arousal nuclei", "LH orexin -> cortex through ascending arousal systems"],
    pathways: ["51,000-83,000 Hcrt-immunoreactive neurons in normal humans", "narcolepsy with cataplexy destroys roughly 90% of this population", "DORA insomnia drugs block OX1R/OX2R"],
    receptors: ["OX1R", "OX2R"],
    taxonomy: ["orexin-A/hypocretin-1", "orexin-B/hypocretin-2"],
    clinical_notes: ["narcolepsy with cataplexy", "insomnia DORA class"],
    citations: cite("thannickal2000"),
  },
  {
    slug: "endocannabinoids",
    name: "Endocannabinoids",
    abbreviation: "eCB",
    color: "#f472b6",
    tier: 2,
    nuclei: ["widespread postsynaptic synthesis sites"],
    projections: ["retrograde presynaptic signaling throughout cortex, basal ganglia, hippocampus, and cerebellum"],
    cell_body_locations: [{ name: "distributed", xyz: [0, 0, 0.4] }],
    projection_fields: ["CB1 presynaptic retrograde signaling", "CB2 immune/microglial emphasis"],
    pathways: ["2-AG", "anandamide", "circuit-specific mechanisms remain debated"],
    receptors: ["CB1", "CB2"],
    taxonomy: ["retrograde lipid signaling", "microglial/immune CB2 emphasis"],
    clinical_notes: ["pain", "appetite", "memory modulation", "psychiatric circuit hypotheses"],
    citations: cite("kano2009"),
  },
];

await writeFile(join(ROOT, "src/data/networks.json"), `${JSON.stringify(networks, null, 2)}\n`);
await writeFile(join(ROOT, "src/data/neuromodulators.json"), `${JSON.stringify(neuromodulators, null, 2)}\n`);

console.log(`Generated ${networks.length} Level 4 network entries and ${neuromodulators.length} Level 5 neuromodulator systems.`);
